In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [ ]:
#loading dataset
df=pd.read_csv('abalone.csv')
df.head(5)

In [ ]:
df.info()

In [ ]:
df.isna().sum()

**no null record**

In [ ]:
df.shape

In [ ]:
# fetch columns in dataset
df.columns

**EDA**

In [ ]:
#setting graph parameters
sns.set_style('darkgrid')
plt.rcParams['figure.figsize']=(20,6)
plt.rcParams['figure.facecolor']='FFFFCB'

In [ ]:
# Rings vs Sex
sns.barplot(x='Rings',y='Sex',data=df)
plt.title('Rings vs Sex')
plt.show()

**Rings count is more in Female(F) then in male(M) n less in Infant(I)**

In [ ]:
#'Length vs Rings'
sns.barplot(x='Length',y='Rings',data=df )
plt.title('Length vs Rings')
plt.show()

**Rings are less with increase in length(-ve correlation) range is between(3.5-17)**

In [ ]:
# 'Diameter vs Rings'
sns.barplot(x='Diameter',y='Rings',data=df)
plt.title('Diameter vs Rings')
plt.show()

**Diameter and rings has +ve correlation rings**

In [ ]:
# Height vs Rings
sns.barplot(x='Height',y='Rings',data=df ,)
plt.title('Height vs Rings')
plt.show()

**Height and Rings having +ve correlationat . at .225 heighest rings count is present around 16. **

In [ ]:
# Whole weight vs Rings
sns.barplot(x='Whole weight',y='Rings',data=df)
plt.title('Whole weight vs Rings')
plt.show()

In [ ]:
# Shucked weight vs Rings
sns.barplot(x='Shucked weight',y='Rings',data=df)
plt.title('Shucked weight vs Rings')
plt.show()

In [ ]:
# Viscera weight vs Rings
sns.barplot(x='Viscera weight',y='Rings',data=df)
plt.title('Viscera weight vs Rings')
plt.show()

In [ ]:
# Shell weight vs Rings
sns.barplot(x='Shell weight',y='Rings',data=df)
plt.title('Shell weight vs Rings')
plt.show()

In [ ]:
sns.countplot(x='Sex' ,data=df)
print(df['Sex'].value_counts())

Data is balanced

In [155]:
# Catagorical data column encoding using ordinal encoder
from sklearn.preprocessing import OrdinalEncoder
onc= OrdinalEncoder()
df['Sex']=onc.fit_transform(df['Sex'].values.reshape(-1,1))

In [156]:
df


Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
0     2.0   0.455     0.365   0.095        0.5140          0.2245   
1     2.0   0.350     0.265   0.090        0.2255          0.0995   
2     0.0   0.530     0.420   0.135        0.6770          0.2565   
3     2.0   0.440     0.365   0.125        0.5160          0.2155   
4     1.0   0.330     0.255   0.080        0.2050          0.0895   
...   ...     ...       ...     ...           ...             ...   
4172  0.0   0.565     0.450   0.165        0.8870          0.3700   
4173  2.0   0.590     0.440   0.135        0.9660          0.4390   
4174  2.0   0.600     0.475   0.205        1.1760          0.5255   
4175  0.0   0.625     0.485   0.150        1.0945          0.5310   
4176  2.0   0.710     0.555   0.195        1.9485          0.9455   

      Viscera weight  Shell weight  Rings  
0             0.1010        0.1500     15  
1             0.0485        0.0700      7  
2             0.1415        0.2100      9  
3             0.1140        0.1550     10  
4             0.0395        0.0550      7  
...              ...           ...    ...  
4172          0.2390        0.2490     11  
4173          0.2145        0.2605     10  
4174          0.2875        0.3080      9  
4175          0.2610        0.2960     10  
4176          0.3765        0.4950     12  

[4177 rows x 9 columns]

In [162]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
target_encoded = encoder.fit_transform(df['Rings'].values)
df['Rings'] = target_encoded
df['Rings']

0       14
1        6
2        8
3        9
4        6
        ..
4172    10
4173     9
4174     8
4175     9
4176    11
Name: Rings, Length: 4177, dtype: int64

**separate out dependent and independent features for train n test purpose**

In [163]:
# x : independent features ,y:dependent features
x=df.drop('Rings',axis=1)
y=df["Rings"]

In [ ]:
# finding out skewness presnt in independent features
x.skew()

considering acceptable range as +/- 0.5 .we can see skewness present in all features:
Height(3.12) ,Whole weight( 0.53) ,Shucked weight(0.71) ,Viscera weight(0.59),Shell weight(0.62) ,Length(-0.64) ,Diameter(-0.61) 


**Dealing with skewness**

In [ ]:

## lets remove skewness (outlier removal) by using power_transform

from sklearn.preprocessing import power_transform
x_new =power_transform(x ,method='yeo-johnson')
cols=['Sex', 'Length', 'Diameter', 'Height', 'Whole weight', 'Shucked weight',
       'Viscera weight', 'Shell weight']
x=pd.DataFrame(x_new ,columns=cols)
# checking skewness after transforming data
x.skew()

We can see skewness in data has been removed 

In [ ]:
df.corr()['Rings'].sort_values(ascending=False)

In [ ]:
df.corr()['Rings'].sort_values(ascending=False).drop(['Rings']).plot(kind='bar',color='c')
plt.xlabel('Features',fontsize=20)
plt.ylabel('Rings')
plt.title('Correlation with target')

highest correlation is with Shell weight  and lowest is with 

In [ ]:
x.head()

#### Data Cleaning : outliers detection

In [ ]:
#outliers detection
x.boxplot(figsize=(20,8))

plt.show()


In [ ]:
# Z score for outlier removal 
from scipy import stats
import numpy as np
 
z = np.abs(stats.zscore(x))
print(z.shape)


In [ ]:
threshold=3
#print index no
print("Indexes at which Outliers are present.")
print(np.where(z>3))


In [ ]:
# No of outliers present
len(np.where(z>3)[0])

In [ ]:
x_new=x.drop([ 163,  166,  236,  237,  238,  306,  694,  719,  720,  891, 1174,
       1209, 1257, 1417, 1428, 1428, 1763, 1987, 2051, 2108, 2161, 2169,
       2171, 2172, 2334, 2381, 2711, 3190, 3902, 3996])

In [ ]:
#% data loss
loss=100-((4177-30)/4177*100)
print("% data loss due to droping outliers is :",loss)

In [ ]:
y.head()

In [ ]:

# function to select for highly correlated features. 
#will remove first feature which is highly correlared with any other feature

def correlation(dataset , threshold):
    col_corr =set() # set of all names of correlated features we have taken st from preventing duplicate entries of columns
    corr_matrix = dataset.corr()
    for i in range(len(corr_matrix.columns)):
        for j in range(i):
            if(corr_matrix.iloc[i,j]> threshold):
                col_name=corr_matrix.columns[i]
                col_corr.add(col_name)
    return col_corr

In [ ]:
#Finding Multicolinearity
cor_features=correlation(x_train ,0.95)
len(cor_features)

In [ ]:
cor_features

In [ ]:
#separate dataset into train and test

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3, random_state=3)
x_train.shape ,x_test.shape

In [ ]:
# using pearson correlation
plt.figure(figsize=(12,8))
cor=x.corr()
sns.heatmap(cor ,annot=True )

In [ ]:
x.corr()

#### Transforming Data to remove skewness

In [ ]:
## lets remove skewness (outlier removal) by using power_transform

from sklearn.preprocessing import power_transform
x_new =power_transform(x ,method='yeo-johnson')
cols=['Sex', 'Length', 'Diameter', 'Height', 'Whole weight', 'Shucked weight',
       'Viscera weight', 'Shell weight']
x=pd.DataFrame(x_new ,columns=cols)
# checking skewness after transforming data
x.skew()

#### start applying classifictaion algorithm

#### Logistic Regression

In [127]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score ,classification_report ,confusion_matrix
lr=LogisticRegression()

**will try to find out best value Random State** 

In [ ]:
max_accu = 0
max_randst = 0
for i in range (0,1000):
    x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2, random_state=i)
    lr.fit(x_train,y_train)
    
    pred_lr=lr.predict(x_test)
    accu_score= accuracy_score(y_test,pred_lr)
    if max_accu<accu_score:
        max_accu= accu_score
        max_randst= i
    if round(accuracy_score(y_train,pred_train)*100 ,1)== round(accuracy_score(y_test,pred_test)*100 ,1):


        

In [120]:
print("max accuracy score is :", round(max_accu*100 ,1),"ar random state :",max_randst)

max accuracy score is : 31.6 ar random state : 152


In [121]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2, random_state=152)

In [122]:
from sklearn.metrics import classification_report
print("Classification report :\n")
print(classification_report(y_test,pred_test))

Classification report :

              precision    recall  f1-score   support

           3       0.00      0.00      0.00         4
           4       0.13      0.18      0.15        11
           5       0.00      0.00      0.00        24
           6       0.00      0.00      0.00        52
           7       0.14      0.18      0.16        71
           8       0.18      0.18      0.18       136
           9       0.18      0.26      0.22       140
          10       0.19      0.25      0.21       137
          11       0.10      0.09      0.09        94
          12       0.00      0.00      0.00        48
          13       0.00      0.00      0.00        32
          14       0.00      0.00      0.00        27
          15       0.00      0.00      0.00        11
          16       0.00      0.00      0.00         9
          17       0.00      0.00      0.00        11
          18       0.00      0.00      0.00         5
          19       0.00      0.00      0.00         7
  

#### Random Forest Classifier

In [123]:
from sklearn.ensemble import RandomForestClassifier


In [126]:
rf = RandomForestClassifier()
rf.fit(x_train,y_train)
predrf=rf.predict(x_test)
print("Accuracy score is :",round(accuracy_score(y_test,predrf)*100 ,2))
print(confusion_matrix(y_test,predrf))
print(classification_report(y_test,predrf))

Accuracy score is : 24.4
[[ 0  4  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  2  5  4  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  6  6  9  3  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  1  5 21 14  7  1  2  1  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  3 14 20 12 16  2  4  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  2  5 28 44 42  8  6  0  0  1  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  1  5 29 48 36 14  1  3  1  1  0  1  0  0  0  0  0  0]
 [ 0  0  0  0  6 12 43 28 39  5  1  1  1  0  1  0  0  0  0  0  0]
 [ 0  0  0  0  1  6 28 23 28  3  4  0  1  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  1  3 12 10 12  3  3  2  0  2  0  0  0  0  0  0  0]
 [ 0  0  0  0  2  2  4  4 14  4  2  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  1  7  9  3  2  1  2  1  1  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  1  2  2  2  0  3  1  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  1  2  3  1  1  0  0  0  0  0  0  1  0  0  0]
 [ 0  0  0  0  0  0  1  2  2  1  2  2  0  1  0  0  

In [137]:
from sklearn.svm import SVC

In [138]:
sv = SVC()
sv.fit(x_train,y_train)
predrf=sv.predict(x_test)
print("Accuracy score is :",round(accuracy_score(y_test,predrf)*100 ,2))
print(confusion_matrix(y_test,predrf))
print(classification_report(y_test,predrf))

Accuracy score is : 30.26
[[ 0  4  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  2  7  2  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  3 10  9  2  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  4 13 29  3  2  1  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  2  6 33 14 14  1  1  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  1  4 31 44 46  9  1  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  5 25 72 34  4  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  4  6 52 56 19  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  2  5 26 38 23  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  1  1 13 20 13  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  1  4 12  5 10  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 11 13  3  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  2  3  5  1  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  1  2  3  3  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  2  5  4  0  0  0  0  0  0  0 

After compairing confusion matrix and Accuracy score SVC model is performing well.
will continue with it

#### Hyper parameter tuning

In [139]:
from sklearn.model_selection import GridSearchCV

In [149]:
#creating parameter list for SVC model to pass to GridSearchCV
parameters={'C': [0.1, 1, 10, 100, 1000],
              'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
              'kernel': ['rbf']}
 

In [150]:
gride = GridSearchCV(SVC(), parameters,cv=5)
gride.fit(x_train,y_train)
gride.best_params_

{'C': 1000, 'gamma': 0.01, 'kernel': 'rbf'}

In [151]:
#prediction with best parameter
gride_pred=gride.best_estimator_.predict(x_test) 
# best score 
accuracy_score(y_test,gride_pred)

0.30861244019138756

In [167]:
import joblib
joblib.dump(gride.best_estimator_,"Abalone.pkl")

['Abalone.pkl']